document.write( '<nav class=\"navbar navbar-expand-sm bg-primary navbar-dark\" style=\"position: sticky;top:0; background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);\" >\n' );
document.write( '      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\n' );
document.write( '        <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '      </button>\n' );
document.write( '      <ul class=\"navbar-nav\">\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\" href="../templates/index.html\">首頁</a>\n' );
document.write( '        </li>\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\" href="../templates/add_team_manager.html\">新增(查詢)成員</a>\n' );
document.write( '        </li>\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\" href="../templates/count_score.html\">計分頁面</a>\n' );
document.write( '        </li>\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\" href=\"../templates/show_sheet.html\">賽程表分析</a>\n' );
document.write( '        </li>\n' );
document.write( '      </ul>\n' );
document.write( '\n' );
document.write( '    </nav>' );
